#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SUBJECT="chizhangucb/chizhang-2"   # the repo getting its own token
STILL_SHARED=("chizhangucb/chronicle" "chizhangucb/factory-fixture")  # still on the shared token

# prove REPO wakes a target and reads the dispatch job's conclusion off the run
# the wake started. A secret that exists and a secret that works are different
# claims (#251), and this is the one that checks the second.
prove() {
  local target="$1" before="" id="" status="" concl="" waited=0 since="" paused="" ids="" candidate=""

  # A paused target skips the dispatch job, so a sweep would prove nothing. Say so
  # now rather than after ten minutes of polling a run that was never going to run.
  # Listed rather than fetched by name: `gh api` on an unset variable answers 404 and
  # prints the error body to stdout, so reading that would take "not paused" for a
  # pause reason on every healthy target. A list exits non-zero only on a real read
  # failure, which is refused rather than read as no pause.
  if ! paused=$(gh variable list --repo "$target" --json name,value \
    --jq '.[] | select(.name=="FACTORY_PAUSED") | .value'); then
    warn "$target: couldn't read its variables, so whether it is paused is unknown"
    return 1
  fi
  if [[ -n "$paused" ]]; then
    warn "$target: FACTORY_PAUSED is set (\"$paused\"), so a sweep proves nothing"
    return 1
  fi

  # Not `|| true`: a read that failed leaves it unknown which runs predate the wake,
  # and a stale run would then pass for a new one, which is the one thing this must
  # not do.
  if ! before=$(gh run list --repo "$target" --workflow factory.yml --event repository_dispatch \
    --limit 1 --json databaseId --jq '.[0].databaseId // ""'); then
    warn "$target: couldn't list runs before the wake, so nothing here could be trusted"
    return 1
  fi
  since=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  say "waking $target"
  if ! gh api --method POST "repos/$target/dispatches" -f event_type=factory-sweep --silent; then
    warn "$target: the wake itself was refused, so nothing was dispatched"
    return 1
  fi

  # A run started after the POST, and carrying a dispatch job. Both clauses matter:
  # the heartbeat and the review workflow send their own repository_dispatch events at
  # these repos, and a factory-update-branch run has no dispatch job at all, so taking
  # the newest run on the event would read someone else's and call the token broken.
  while (( waited < 120 )); do
    sleep 3; waited=$((waited + 3))
    ids=$(gh run list --repo "$target" --workflow factory.yml --event repository_dispatch \
      --limit 10 --json databaseId,createdAt \
      --jq "[.[] | select(.createdAt >= \"$since\")] | reverse | .[].databaseId" 2>/dev/null || true)
    for candidate in $ids; do
      [[ "$candidate" == "$before" ]] && continue
      if gh run view "$candidate" --repo "$target" --json jobs \
           --jq '.jobs[] | select(.name | startswith("dispatch")) | .name' 2>/dev/null | grep -q .; then
        id="$candidate"; break
      fi
    done
    [[ -n "$id" ]] && break
  done
  if [[ -z "$id" ]]; then
    warn "$target: no sweep run with a dispatch job appeared within 120s of the wake"
    return 1
  fi
  note "  run $id"

  waited=0
  while (( waited < 600 )); do
    status=$(gh run view "$id" --repo "$target" --json status --jq .status 2>/dev/null || echo "")
    [[ "$status" == "completed" ]] && break
    sleep 10; waited=$((waited + 10))
  done
  if [[ "$status" != "completed" ]]; then
    warn "$target: run $id still $status after 10 minutes"
    return 1
  fi

  concl=$(gh run view "$id" --repo "$target" --json jobs \
    --jq '.jobs[] | select(.name | startswith("dispatch")) | .conclusion')
  case "$concl" in
    success) printf '  %s✓%s %s: dispatch succeeded\n' "$GREEN" "$RESET" "$target" ;;
    skipped) warn "$target: dispatch was SKIPPED, so nothing was proved. FACTORY_PAUSED set?"; return 1 ;;
    *)       printf '  %s✗%s %s: dispatch %s, see %s\n' "$RED" "$RESET" "$target" \
               "${concl:-missing (job never instantiated: paused, or the caller is out of date)}" \
               "$(gh run view "$id" --repo "$target" --json url --jq .url)"; return 1 ;;
  esac
}

banner "chizhang-2 gets its own token (#251)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Mint a token scoped to chizhang-2 alone"
say "chizhang-2 is private and confidential. The shared FACTORY_PAT lives in"
say "public chronicle's secret store, so it must stop reaching chizhang-2."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: factory-chizhang-2"
step "Resource owner: chizhangucb. Expiration: your usual."
step "Repository access: Only select repositories → chizhang-2, and nothing else."
step "Repository permissions, all Read and write:"
step "    Contents · Issues · Pull requests · Workflows"
note "    (Metadata read is added for you. Nothing else: the factory posts commit"
note "     statuses and writes repo variables with other credentials by design.)"
step "Generate token, then copy it."
confirm "Does its repository access name chizhang-2 and no other repo?" || {
  warn "Go back and fix it. A token reaching further than chizhang-2 does not close #251."
  exit 1
}

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Set it as FACTORY_PAT on chizhang-2"
say "Pasted hidden, piped straight to gh. It is not written to disk or echoed."
ask_secret NEW_PAT "Paste the new token:"
if [[ -z "${NEW_PAT:-}" ]]; then
  warn "nothing pasted, so stop here. Carrying on would prove the OLD shared token in"
  warn "stage 3 and then withdraw it in stage 4, leaving chizhang-2 with no credential."
  warn "Set it by hand and re-run: gh secret set FACTORY_PAT --repo $SUBJECT"
  SKIPPED+=("FACTORY_PAT on $SUBJECT")
  finish
  exit 1
fi
printf '%s' "$NEW_PAT" | gh secret set FACTORY_PAT --repo "$SUBJECT"
NEW_PAT=""
printf '  %s✓ set%s FACTORY_PAT on %s\n' "$GREEN" "$RESET" "$SUBJECT"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Prove the new token works"
say "Before withdrawing the old reach, check the new token actually carries the"
say "permissions the factory needs rather than only existing."
prove "$SUBJECT" || {
  warn "Stop here. Fix the token's permissions before stage 4, or chizhang-2"
  warn "loses both credentials at once."
  confirm "Carry on anyway?" || exit 1
}
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Withdraw the shared token's reach into chizhang-2"
say "This is the step that closes the hole. Adding a new token without it"
say "leaves the path from the public repo's secret store open."
open_url "https://github.com/settings/tokens?type=beta"
step "Open the shared factory token (the one chronicle and factory-fixture use)."
step "Repository access → Only select repositories → remove chizhang-2."
step "Leave chronicle and factory-fixture selected. Change no permissions."
step "Update token. This does not change the token's value, so no secret is restamped."
confirm "chizhang-2 removed from the shared token's repository access?" || {
  SKIPPED+=("removing chizhang-2 from the shared token's repository access")
  warn "recorded as still to do: the ticket is not closed until this is done"
}

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Prove the change, after the change"
say "chizhang-2 on its new token, and the two repos still on the shared one,"
say "all woken and read the same way now the scope edit has landed."
FAILED=()
for t in "$SUBJECT" "${STILL_SHARED[@]}"; do prove "$t" || FAILED+=("$t"); done
if (( ${#FAILED[@]} )); then
  warn "dispatch failing on: ${FAILED[*]}"
  warn "re-check the repository access of whichever token covers those repos."
  SKIPPED+=("dispatch failing on ${FAILED[*]}")
fi
pause

finish
say "Close #251 when every box above is ticked. chronicle and factory-fixture"
say "moving to their own tokens is #253."
printf '\n'
# Anything on the still-to-do list means the hole is open or a target is not
# dispatching, so the wizard must not exit 0 on it.
if (( ${#SKIPPED[@]} )); then exit 1; fi
